feat(gossip): data source metrics
Syndica/sig pull request #266
Opened 2024-09-05 13:00 UTC by sonicfromnewyoke

attempt to close #121

2024-09-09 22:49 UTC, Sobeston commented
Looks all good so far :+1:

2024-09-23 13:31 UTC, 0xNineteen requested changes
the main thing we want to track is when values are successfully **inserted** and **updated** in two separate metrics

2024-09-23 13:31 UTC, 0xNineteen commented on src/gossip/service.zig
> +            self.stats.table_n_updates_pull_req.add(pull_requests.items.len);
`gossip_table.insert` will fail with an error if the value was not inserted which is not accounted for in this case -- would need to add logic to the catch block

2024-09-23 13:31 UTC, 0xNineteen commented on src/gossip/service.zig
> +                self.stats.table_n_updates_pull_resp.add(timeout_indexs.items.len);
same here -- but we need to look at `insertValues` in the lines above

2024-09-23 13:31 UTC, 0xNineteen commented on src/gossip/service.zig
> +            self.stats.table_n_updates_push_msg.inc();
same here

2024-09-25 16:22 UTC, 0xNineteen commented
closed for #276

2024-09-25 16:22 UTC, closed without merging