fix(cmd): move resolveSocketAddr into net
Syndica/sig pull request #427
Opened 2024-12-06 20:35 UTC by 0xNineteen

2024-12-06 20:36 UTC, 0xNineteen commented
* **#427** <a href="https://app.graphite.dev/github/pr/Syndica/sig/427?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/Syndica/sig/427?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-09 13:37 UTC, dnut requested changes

2024-12-09 13:37 UTC, dnut commented on src/net/net.zig
> +}
```suggestion
pub fn resolveSocketAddr(allocator: std.mem.Allocator, host_and_port: []const u8) !SocketAddr {
    const domain_port_sep = std.mem.indexOfScalar(u8, host_and_port, ':') orelse {
        return error.PortMissing;
    };
    const domain_str = host_and_port[0..domain_port_sep];
    if (domain_str.len == 0) {
        return error.DomainNotValid;
    }
    // parse port from string
    const port = std.fmt.parseInt(u16, host_and_port[domain_port_sep + 1 ..], 10) catch {
        return error.PortNotValid;
    };

    // get dns address lists
    const addr_list = try std.net.getAddressList(allocator, domain_str, port);
    defer addr_list.deinit();

    if (addr_list.addrs.len == 0) {
        return error.DnsResolutionFailure;
    }

    // use first A record address
    const ipv4_addr = addr_list.addrs[0];

    const socket_addr = SocketAddr.fromIpV4Address(ipv4_addr);
    std.debug.assert(socket_addr.port() == port);
    return socket_addr;
}
```

2024-12-09 14:10 UTC, dnut approved these changes

2024-12-09 18:20 UTC, merged