feat(logs): add alloy + loki
Syndica/sig pull request #451
Opened 2024-12-18 12:15 UTC by 0xNineteen

2024-12-18 12:15 UTC, 0xNineteen commented
* **#451** <a href="https://app.graphite.dev/github/pr/Syndica/sig/451?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/Syndica/sig/451?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2025-01-03 22:31 UTC, Sobeston requested changes
Had a few hitches getting things up, but seems generally good.

2025-01-03 22:31 UTC, Sobeston commented on metrics/compose_linux.yaml
> +    image: grafana/loki:3.0.0
Do we really need these network_mode: host things? Seems like I get everything connecting to each other without it. If we can drop that, we can clean up to have just one compose.yml

2025-01-03 22:31 UTC, Sobeston commented on metrics/loki/loki.yml
> +
I had to add this block to get grafana to show logs:

```yml

limits_config:
  volume_enabled: true
```

2025-01-03 22:32 UTC, Sobeston commented
Prometheus doesn't seem to like us sending empty content headers, its logs are spammed with it.

Seems we can just do this?

```zig
pub fn getMetrics(
    self: *const MetricsEndpoint,
    _: *httpz.Request,
    response: *httpz.Response,
) !void {
    response.content_type = .TEXT; // <- make prom happy
    try self.registry.write(self.allocator, response.writer());
}
```

2025-01-03 22:33 UTC, Sobeston commented
Prometheus also doesn't appreciate us using
```api_version: v1```
it expects v2 these days.

```
prometheus     | time=2025-01-03T22:33:25.654Z level=ERROR source=main.go:593 msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="parsing YAML file /etc/prometheus/prometheus.yml: expected Alertmanager api version to be one of [v2] but got v1"
prometheus exited with code 2
```

2025-01-06 12:28 UTC, dnut reviewed
Looks good, but I just had a few minor nitpicks. I'm not very opinionated about any of this, so feel free to turn them down.

2025-01-06 12:28 UTC, dnut commented on metrics/README.md
> +- sig gossip metrics are published to localhost:12355
redundant with prior bullet

2025-01-06 12:28 UTC, dnut commented on metrics/docker-compose.yml
> +      - "3100:3100"
Is there a reason to expose these ports to the host system? This shouldn't be necessary just to connect from other containers in the same docker network.

2025-01-06 12:28 UTC, dnut commented on metrics/docker-compose.yml
> +      - "../logs:/var/log/alloy"
Not very important at this point, but it's a good practice to mount as read-only if you know the files don't need to be modified by the container. Does `config.alloy` need to be modified by the application?
```suggestion
      - "./alloy/config.alloy:/etc/alloy/config.alloy:ro"
      - "../logs:/var/log/alloy:ro"
```

2025-01-06 12:28 UTC, dnut commented on metrics/docker-compose.yml
> +      - ./loki:/etc/loki
```suggestion
      - ./loki:/etc/loki:ro
```

2025-01-06 12:28 UTC, dnut commented on src/prometheus/http.zig
> +    response.content_type = .TEXT; // expected by prometheus
what happens when you don't include this?

2025-01-06 12:28 UTC, dnut commented on .gitignore
> +/logs
Do we need a logs folder? I feel like it's slightly easier to work with a log file when it's placed directly in the current working directory. Doesn't make much difference but just a small convenience.

Also I don't see where a log file is being produced by the code.

2025-01-06 15:05 UTC, Sobeston commented on src/prometheus/http.zig
> +    response.content_type = .TEXT; // expected by prometheus
Prometheus doesn't record it at all.
```
prometheus     | time=2025-01-06T15:04:39.954Z level=ERROR source=scrape.go:1590 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=prometheus target=http://host.docker.internal:12345/metrics content_type="" fallback_media_type="" err="non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target"
```

2025-01-06 15:14 UTC, Sobeston commented on src/prometheus/http.zig
> +    response.content_type = .TEXT; // expected by prometheus
I have no idea - worth noting that our prometheus image doesn't have a version on it, pretty sure that means we're tracking the latest image, which is probably undesirable.

2025-01-06 18:59 UTC, 0xNineteen commented on metrics/docker-compose.yml
> +      - "3100:3100"
sobe reconfigured it to not use host mode anymore

2025-01-06 19:04 UTC, 0xNineteen commented on metrics/README.md
> +- sig gossip metrics are published to localhost:12355
addressed - messed up the commit on this one mb

2025-01-06 19:04 UTC, 0xNineteen commented on metrics/docker-compose.yml
> +      - "../logs:/var/log/alloy"
addressed

2025-01-06 19:04 UTC, 0xNineteen commented on metrics/docker-compose.yml
> +      - ./loki:/etc/loki
addressed

2025-01-06 19:09 UTC, dnut commented on metrics/docker-compose.yml
> +      - "3100:3100"
Yeah I noticed that. By default all the containers from a compose file share the same docker network with all ports exposed to the other containers in that network. This line exposes it to the host system, which seems unnecessary, unless you're connecting to it from outside of docker.

2025-01-06 19:10 UTC, 0xNineteen commented on src/prometheus/http.zig
> +    response.content_type = .TEXT; // expected by prometheus
added a version - 01654a9f

2025-01-06 19:11 UTC, 0xNineteen commented on .gitignore
> +/logs
log files are created through cmd and explained in readme -- see below -- would require changes to how we do logging which we can do in another PR if we want

```
## Run with logs

`./zig-out/bin/sig gossip -n testnet 2>&1 | tee -a logs/sig.log
```

2025-01-06 21:04 UTC, Sobeston requested changes

2025-01-06 21:04 UTC, Sobeston commented on metrics/.env
> +SLACK_WEBHOOK_URL=https://hooks.slack.com/
PR seems good, just this one line - what uses it?

2025-01-06 21:08 UTC, dnut commented on .gitignore
> +/logs
I don't see how it's more organized when there's only one log file. But I guess it doesn't really matter.

2025-01-06 21:27 UTC, 0xNineteen commented on metrics/.env
> +SLACK_WEBHOOK_URL=https://hooks.slack.com/
ah somehow trickled in from branch above - removed it - 6627ce33

2025-01-06 21:54 UTC, Sobeston approved these changes
:shipit:

2025-01-06 22:12 UTC, merged