fix(ledger): fuzz testing
Syndica/sig pull request #452
Opened 2024-12-18 14:30 UTC by dadepo

2024-12-19 17:47 UTC, dadepo commented
```
$ zig build fuzz -- ledger_rocksdb 10 1_000_000 > output.txt 2>&1
$ grep -c 'Put actions' output.txt
890
$ grep -c 'Delete actions' output.txt
889
$ grep -c 'Delete Files in Range actions' output.txt
925
$ grep -c 'getBytes actions' output.txt
10
$ grep -c 'get actions' output.txt
11
$ grep -c 'count actions' output.txt
997
$ grep -c 'contains actions' output.txt
11
$ grep -c 'Batch actions' output.txt
904
```

`get`, `getBytes` and `contains` are order of magnitude slower. Need to investigate

2025-01-06 18:42 UTC, 0xNineteen requested changes
one thing thats great about this is that it performs many actions in parallel and if something errors it will break and catch it - however, theres no consistency check that the values which are read, are what they should be - which i think we care about - since we have multiple database backends, i think this should be simple to do: perform the same operations and after each 'step' ensure they are returning equivalent values -- the accountsdb fuzzer does this which could be a reference

2025-01-06 18:42 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +const build_options = @import("build-options");
can we keep all imports at the top

2025-01-06 18:42 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +    var db: BlockstoreDB = try BlockstoreDB.open(
```suggestion
    var db = try BlockstoreDB.open(
```

2025-01-06 18:42 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +    defer db.deinit();
```suggestion
    defer db.deinit();
```

2025-01-06 18:42 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +    };
since the values are random -- i think this is the same but simpler
```suggestion
    const start = random.int(u32);
    const end = random.int(u32) +| start;
```

2025-01-06 18:42 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +        };
same here

2025-01-06 18:42 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +        try batch.put(cf1, key, Data{ .value = value });
why have a put in a delete range?

2025-01-07 14:09 UTC, dnut requested changes
Ideally a fuzzer would be deterministic and reproducible. When a fuzz test fails you should be able to use the same seed to trigger the same error and debug what went wrong. But in this case, the multithreaded behavior is random and not reproducible by using the same seed. I do see the value of identifying issues with concurrency though, and I'm not sure how to test that in a reproducible way. Any thoughts?

Also I noticed stdout is flooded very fast with a ton of text when running these fuzz tests. It might be good to slow that down a bit. Normally, for fuzz tests, I would use stdout to print one line for each discrete test case that can be individually reproduced using a particular seed that is included on that line. Something on the order of 1 log message per second seems reasonable.

This test only deals with the database implementation which is a pretty small part of the ledger. In the future we should write some fuzz tests for the ShredInserter and BlockstoreReader, which is where I would expect to see more problems than RocksDB for example.

2025-01-10 14:28 UTC, dadepo commented on src/ledger/fuzz.zig
> +const build_options = @import("build-options");
https://github.com/Syndica/sig/pull/452/commits/c7efe51d70e31b6f8575e2298fa7793946060cb4

2025-01-10 14:28 UTC, dadepo commented on src/ledger/fuzz.zig
> +    var db: BlockstoreDB = try BlockstoreDB.open(
https://github.com/Syndica/sig/pull/452/commits/52bbbb212263ef81abab187ef584661a398f4f94

2025-01-10 14:30 UTC, dadepo commented on src/ledger/fuzz.zig
> +    defer db.deinit();
Can't find the exact commit but this has also been processed. The extra newline was removed.

2025-01-10 14:32 UTC, dadepo commented on src/ledger/fuzz.zig
> +    };
Applied as part of the commit that checks the methods return expected output

https://github.com/Syndica/sig/pull/452/commits/9e06b51485f7c019d6d2404e4ade42e270ac008a

2025-01-10 14:32 UTC, dadepo commented on src/ledger/fuzz.zig
> +        };
Applied as part of the commit that checks the methods return expected output

https://github.com/Syndica/sig/pull/452/commits/9e06b51485f7c019d6d2404e4ade42e270ac008a

2025-01-10 14:33 UTC, dadepo commented on src/ledger/fuzz.zig
> +        try batch.put(cf1, key, Data{ .value = value });
This is because the batch API is being performed, which involves batching the put and the delete actions.

2025-01-10 14:34 UTC, dadepo commented on src/ledger/fuzz.zig
> +    }
Applied while removing the concurrency. https://github.com/Syndica/sig/pull/452/commits/b419b4becebf3ad18e872e4005915161f9f2f91a

2025-01-10 14:38 UTC, dadepo commented on src/ledger/fuzz.zig
> +    }
https://github.com/Syndica/sig/pull/452/commits/9cfe206d3892210badb757d709a503a1f37e6f32

> Also, what is the purpose of this defer fetchAdd?

That was a mistake. Removed.

2025-01-10 14:43 UTC, dadepo commented on src/ledger/fuzz.zig
> +        try std.fmt.allocPrint(allocator, "{s}/ledger/rocksdb", .{sig.FUZZ_DATA_DIR});
https://github.com/Syndica/sig/pull/452/commits/076d4b323de44d8407ebaa3520d824a53db535de

2025-01-10 14:43 UTC, dadepo commented on src/ledger/fuzz.zig
> +        "RocksDb.put",
https://github.com/Syndica/sig/pull/452/commits/076d4b323de44d8407ebaa3520d824a53db535de

2025-01-10 14:43 UTC, dadepo commented on src/ledger/fuzz.zig
> +    random: *const std.rand.Random,
https://github.com/Syndica/sig/pull/452/commits/3e07071e964b0ed5a4f31f7aa7e0345285187829

2025-01-10 14:44 UTC, dadepo commented on src/ledger/fuzz.zig
> +        const current_count = count.load(.monotonic);
All of the atomics has been removed as part of dropping the concurrency https://github.com/Syndica/sig/pull/452/commits/b419b4becebf3ad18e872e4005915161f9f2f91a

2025-01-10 14:46 UTC, dadepo commented on src/ledger/fuzz.zig
> +        .{ db, cf1, key },
> I think it would be a more thorough test if it actually returned true sometimes.

I think this should now be the case.

2025-01-10 15:16 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +    defer db.deinit();
its still there 
```
    var db = try createBlockstoreDB();

    defer db.deinit();
```

2025-01-10 15:28 UTC, 0xNineteen requested changes

2025-01-10 15:28 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +    }
i feel like it would be better to have a similar approach to accountsdb where you have a enum over all functions and then randomly select which function to run and have a single max-actions to run would be better/more random

2025-01-10 15:28 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +var dataKeys = std.ArrayList(u32).init(allocator);
i dont think we actually need this - we can just use dataMap.keys() when we need to

2025-01-10 15:28 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +var dataMap = std.AutoHashMap(u32, Data).init(allocator);
might want to add a doc-comment above this explaning that this is a simpler blockstore which we will use to make sure our data is up to date -- also since its initialized it should be `data_map`

2025-01-10 15:28 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +            // Commit batch put and delete range.
if these methods dont modify the dataMap - then we should probably add a note saying there is no confirmation in these methods

2025-01-10 16:04 UTC, dadepo commented on src/ledger/fuzz.zig
> +    }
> i feel like it would be better to have a similar approach to accountsdb where you have a enum over all functions and then randomly select which function to run 

I considered this, but the reasoning why I did not go with that approach was because I felt the randomness should be in how the methods are called (ie the inputs passed to them) and not if the methods we are called - which would be the case if the fuzz tests randomly selects the methods to execute while fuzzing.

The advantage of going with the enum approach is for dependencies between the method calls and if randomizing that would expose any hidden bugs.

I think it should be possible to adapt what is there now to that. I'll give it a shot

2025-01-10 16:05 UTC, dadepo commented on src/ledger/fuzz.zig
> +var dataKeys = std.ArrayList(u32).init(allocator);
I actually had that but had some issues. So just quickly went with keeping a separate list. I'll revisit this and see if I can drop it

2025-01-10 19:58 UTC, dnut commented on src/ledger/fuzz.zig
> +    }
>  I felt the randomness should be in how the methods are called (ie the inputs passed to them) and not if the methods we are called

why not both? more variability here seems like a bonus

2025-01-13 11:19 UTC, dadepo commented on src/ledger/fuzz.zig
> +var dataKeys = std.ArrayList(u32).init(allocator);
> I actually had that but had some issues.

It was the fact that `AutoHashMap` don't have `.keys()` method, but it only returns a keyIterator. So added a separate list to quickly get going

Dropped it in [c695ce7](https://github.com/Syndica/sig/pull/452/commits/c695ce776cf0e94aa2a502233de86c3696196a62)

2025-01-13 11:22 UTC, dadepo commented on src/ledger/fuzz.zig
> +var dataMap = std.AutoHashMap(u32, Data).init(allocator);
[e29fef7](https://github.com/Syndica/sig/pull/452/commits/e29fef7149e4106793db48735e2411d147b9fb94)

2025-01-13 12:09 UTC, dadepo commented on src/ledger/fuzz.zig
> +            // Commit batch put and delete range.
[0688ef9](https://github.com/Syndica/sig/pull/452/commits/0688ef9b24d019d4b10ab23d0ccdebcdf0d9a7dd)

2025-01-13 12:09 UTC, dadepo commented on src/ledger/fuzz.zig
> +    }
[c695ce7](https://github.com/Syndica/sig/pull/452/commits/c695ce776cf0e94aa2a502233de86c3696196a62)

2025-01-13 16:32 UTC, 0xNineteen commented on src/ledger/fuzz.zig
> +var dataKeys = std.ArrayList(u32).init(allocator);
should still be `data_map`

2025-01-13 16:33 UTC, 0xNineteen submitted a review, later dismissed
lgtm :shipit:

2025-01-14 19:07 UTC, dnut commented on src/ledger/fuzz.zig
> +    random: *const std.rand.Random,
FYI `std.rand` is an alias for `std.Random`. Random contains an alias to itself only for compatibility with code written for old versions where `std.rand` was a separate namespace.

2025-01-14 19:59 UTC, dnut commented on src/ledger/fuzz.zig
> +        .{ db, cf1, key },
Now it's going to return true 100% of the time instead of 0% of the time. I was suggesting that the behavior should be variable. 50% of the time would be nice.

2025-01-14 20:08 UTC, dnut commented
> > Also I noticed stdout is flooded very fast with a ton of text when running these fuzz tests. It might be good to slow that down a bit. Normally, for fuzz tests, I would use stdout to print one line for each discrete test case that can be individually reproduced using a particular seed that is included on that line. Something on the order of 1 log message per second seems reasonable.
> 
> This should be addressed now. I got the idea for logging every 1000 count from another fuzzer in the codebase. But I've dropped it now.

You've removed all printing. I was suggesting that there should be discrete test cases that are actually printed.

Here's the problem I'm trying to address. I just ran the fuzzer for a long time. Maybe 20 minutes. The fuzzer eventually crashed due to an error in a test. I'd like to reproduce this, but the only way to do that is by running the fuzzer again for 20+ minutes. Identifying the cause of this failure will not be easy.

If instead the fuzzer ran many distinct and isolated test cases, and it printed the seed for each case, it would be easy to rerun a single one of those cases when they fail. You can look at the allocator fuzzer to see what I mean.

2025-01-15 12:08 UTC, dadepo commented
> If instead the fuzzer ran many distinct and isolated test cases, and it printed the seed for each case, it would be easy to rerun a single one of those cases when they fail. You can look at the allocator fuzzer to see what I mean.

The allocator fuzzer seems to have a different structure. It allows fuzzing two different implementations (disk or batch) or both and provides ability to select which to run. 

This is different from the structure for the ledger fuzzing as it fuzzes various methods on the same ledger implementation. And the pattern used for it is similar to what is used for the accounts db, and gossip fuzzer.

> Here's the problem I'm trying to address. I just ran the fuzzer for a long time. Maybe 20 minutes. The fuzzer eventually crashed due to an error in a test. I'd like to reproduce this, but the only way to do that is by running the fuzzer again for 20+ minutes. Identifying the cause of this failure will not be easy.

I am not sure if it is possible to shortcut this, as it may be that it requires that much time for the random interaction of the methods being fuzzed to trigger the issue.

2025-01-15 12:10 UTC, dadepo commented
> I got the idea for logging every 1000 count from another fuzzer in the codebase. But I've dropped it now.

Checked again. This is was from `gossip_fuzz_service`.

2025-01-15 13:07 UTC, dnut commented
> The allocator fuzzer seems to have a different structure. It allows fuzzing two different implementations (disk or batch) or both and provides ability to select which to run.

This is not the relevant part of the fuzzer that I'm talking about. You can say the same thing about the ledger fuzzer allowing multiple databases. It just happens to deal with that abstraction at comptime whereas the allocator fuzzer does it at runtime. But this is a separate concern.

> This is different from the structure for the ledger fuzzing as it fuzzes various methods on the same ledger implementation. And the pattern used for it is similar to what is used for the accounts db, and gossip fuzzer.

This is exactly the same pattern followed by the allocator fuzzer.

> > Here's the problem I'm trying to address. I just ran the fuzzer for a long time. Maybe 20 minutes. The fuzzer eventually crashed due to an error in a test. I'd like to reproduce this, but the only way to do that is by running the fuzzer again for 20+ minutes. Identifying the cause of this failure will not be easy.
> 
> I am not sure if it is possible to shortcut this, as it may be that it requires that much time for the random interaction of the methods being fuzzed to trigger the issue.

I agree it's not going to be possible to shortcut that specific scenario. The idea is to create different scenarios that can be reproduced

2025-01-15 14:39 UTC, dadepo commented
> instead it could look like something like this:
> 
> ```zig
> while (true) {
>      seed += 1;
>      print("using seed: {}", .{seed});
>      const random = rng(seed).random();
>      for (0..test_case_size) |_| {
>           runIteration(random);
>      }
> }
> ```

I am not sure I follow the intended benefit here. Given that the number of runs depends on `test_case_size` what this modification does is to add 1 to the provided seed and used that to run the iteration.  

If the intention is to get to the seed that caused the issue faster,  I am also not sure if the proposal solves the original problem statement. Given that if an error is triggered at `seed:10`, that does not make it easier to be reproduced using that `seed:10` directly. This is because the test is stateful, and the error case that appeared at `seed:10` might be because of the 9 previous seed runs.

Also to be sure I am on the same page with the proposed improvement, is the current ledger fuzzer implementation similarly in structure to exiting fuzzer like accounts_db and gossip? and is the proposed modification something that would also need to be applied to existing fuzzer? If that is the case, what about discussing the proposed improvement separately (as I am still not sure I follow how it solves the intended problem)  - and then apply to all the other fuzzers if it improves things?

2025-01-15 15:30 UTC, dnut commented
It solves the problem if you reset the state for each test case. I was just giving a basic pseudocode example to express the general idea. I wasn't trying to write the code that solves the problem in its entirety. At that point I think it's more efficient to just make the change in the code, so I committed it already.

Regarding gossip and accountsdb, I do think those fuzzers are flawed and need to be reworked, but that's not in scope right now. I just think we should not be adding more fuzzers that have the same flaw.

2025-01-15 15:30 UTC, dnut approved these changes

2025-01-15 15:43 UTC, dnut approved these changes

2025-01-15 15:51 UTC, dadepo commented
@dnut I think the recent changes might not be working as intended.

Running

`zig build fuzz -Dblockstore=rocksdb -- ledger 10 10 -freference-traced`

continually prints:

```
action_name reached max actions: 10
action_name reached max actions: 10
action_name reached max actions: 10
```

Until I kill the process. 

Also the `action_name` bit is not providing the intended information on which action is being executed.

2025-01-15 15:57 UTC, merged

2025-01-15 16:49 UTC, dnut commented
My mistake. I thought you added this to CI. I'll open a pr to add it to CI and fix the loop issue.

2025-01-15 17:25 UTC, dadepo commented on src/ledger/fuzz.zig
> +        for (0..1_000) |_| {
@dnut The benefit of this change is that the seed used is not just the one passed in.  The observation though is that, this fixes the iteration for each seed at 1000. - which may seem arbitrary. 

It would probably be an improvement to have this configurable (which will differ from the other fuzzer) or

Do not change the seed value like this put have a random value generated by CI.