perf(networking): improve socket io
Syndica/sig pull request #465
Opened 2024-12-19 14:46 UTC by kprotty

2025-02-03 21:50 UTC, Sobeston requested changes
Some small nits, overall seems good

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
>          allocator: Allocator,
Does it make sense to have an allocator per-node?

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +    var register = std.atomic.Value(?*List.Node).init(null);
Looks like you could use std.once here? Though might not be an improvement

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +        if (ref_count.fetchAdd(2, .acquire) == 0) {
Is this meant to be 2?

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +        _: ?*void,
Is this param necessary?

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +            iter = node.next;
Could put the next in the while's continue expression?

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +        if (ref_count.fetchAdd(2, .acquire) == 0) {
Seems intentional, would be good to comment why

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +        maybe_timer.?.run(loop, completion, SOCKET_TIMEOUT_US, xev.Timer, maybe_timer, onTick);
We take the timer as an optional, and then almost immediately assert it isn't

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +        maybe_timer.?.run(loop, completion, SOCKET_TIMEOUT_US, xev.Timer, maybe_timer, onTick);
Okay, seems the optional is required to satisfy libxev's types? In this case, maybe just not use the "maybe_" param names on functions where we actually require it.

2025-02-03 21:50 UTC, Sobeston commented on src/net/socket_utils.zig
> +        _: ?*void,
Ignore me, required for libxev's types.

2025-02-03 22:49 UTC, kprotty commented on src/net/socket_utils.zig
> +    var register = std.atomic.Value(?*List.Node).init(null);
Needs to track deinit + support being initialized multiple times i.e. during test/benchmark

2025-02-03 22:49 UTC, kprotty commented on src/net/socket_utils.zig
>          allocator: Allocator,
SocketThreads which make the Nodes could be created with diffferent allocators

2025-02-03 22:49 UTC, kprotty commented on src/net/socket_utils.zig
> +            iter = node.next;
`closeNode()` could dealloc the node so the continue expr would ref invalid memory

2025-02-03 23:48 UTC, kprotty commented on src/net/socket_utils.zig
> +        maybe_timer.?.run(loop, completion, SOCKET_TIMEOUT_US, xev.Timer, maybe_timer, onTick);
https://github.com/Syndica/sig/pull/465/commits/693219d352ad864800c5ad9da20211113ba6afab

2025-02-03 23:48 UTC, kprotty commented on src/net/socket_utils.zig
> +        if (ref_count.fetchAdd(2, .acquire) == 0) {
https://github.com/Syndica/sig/pull/465/commits/693219d352ad864800c5ad9da20211113ba6afab

2025-02-04 00:43 UTC, Sobeston approved these changes
All looks good

2025-02-04 12:47 UTC, merged